language: objective-c

osx_image: xcode7.3

script:
 - ./gradlew clean build coverage coveralls -Dscan --configure-on-demand --parallel --stacktrace

after_script:
 - ./gradlew simulatorKill

sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle
